services:
  - type: web
    name: strupay-admin
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        value: 8313827376:AAFkevZQbO_ppTWd6cAJ96UrvFJHw9mKqKg
      - key: TELEGRAM_CHAT_ID
        value: 2103408372
    plan: free
